eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign111
    thymeleaf.encoding: UTF-8
    thymeleaf.servlet.content-type: text/html
  main:
    allow-bean-definition-overriding: true
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true

